### ISSUE TITLE
NestJS providers are not injected expectedly

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/next#58]
### Describe the bug

backend의 `pnpm start` 명령어가 동작하지 않습니다.
Test 시 mocking을 위해 세팅해둔 custom provider(`@Inject`)가 제대로 동작하지 않는 것이 원인으로 보입니다.

### Reproduction

```
cd backend
pnpm start
```

### Logs

```
$ pnpm start

> backend@ start /data/data/com.termux/files/home/next/backend
> nest start

[Nest] 23471  - 06/23/2022, 7:19:44 PM     LOG [NestFactory] Starting Nest application...
[Nest] 23471  - 06/23/2022, 7:19:44 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AuthService (?). Please make sure that the argument prisma at index [0] is available in the AuthModule context.
                                                                       Potential solutions:
- If prisma is a provider, is it part of the current AuthModule?
- If prisma is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing prisma */ ]
  })

Error: Nest can't resolve dependencies of the AuthService (?). Please make sure that the argument prisma at index [0] is available in the AuthModule context.

Potential solutions:
- If prisma is a provider, is it part of the current AuthModule?
- If prisma is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing prisma */ ]
  })                                                                   
    at Injector.lookupComponentInParentModules (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/injector.js:231:19)
    at Injector.resolveComponentInstance (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/injector.js:184:33)
    at resolveParam (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/injector.js:106:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/injector.js:121:27)
    at Injector.loadInstance (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at /data/data/com.termux/files/home/next/node_modules/.pnpm/@nestjs+core@8.4.1_aotyriplbp4tu63e5hhjmur6ey/node_modules/@nestjs/core/injector/instance-loader.js:29:13
 ELIFECYCLE  Command failed with exit code 1.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by cranemont** [comment]
Custom Provider의 token을 지정해주지 않아서 생기는 문제로 보입니다. 아래처럼 설정해주면 잘 실행됩니다

```typescript
// prisma.module.ts
import { Global, Module } from '@nestjs/common'
import { PrismaService } from './prisma.service'

const customPrismaProvider = {
  provide: 'prisma',
  useClass: PrismaService
}

@Global()
@Module({
  providers: [customPrismaProvider],
  exports: [customPrismaProvider]
})
export class PrismaModule {}
```

```typescript
//auth.module.ts
import { Module } from '@nestjs/common'
import { AuthController } from './auth.controller'
import { AuthService } from './auth.service'

const customAuthProvider = {
  provide: 'auth',
  useClass: AuthService
}

@Module({
  controllers: [AuthController],
  providers: [customAuthProvider]
})
export class AuthModule {}
```

**Comment by cranemont** [comment]
issue 해결과는 별개로 혹시 constructor-based injection를 사용하지 않는 이유가 있을까요? mocking을 위해서라면 [이 예시 코드](https://gist.github.com/rinogo/443875a738fc05f95dc740315afa6f77)처럼 test 파일 내에서만 `useValue`를 사용해서 mocking해도 되지 않을까 하는 생각이 들어서요

**Comment by aintbe** [comment]
> Warning
If your class doesn't extend another provider, you should always prefer using constructor-based injection.

공식 문서에서도 inject하려는 클래스에 상속 관계가 없다면 constructor-based injection을 권장하고 있기는 합니다! 이유는 명시되지 않았지만, property-based를 쓰는 이유가 `super()` call을 줄이기 위해서인데 상속 관계가 없다면 이유 없이 코드만 길어지는 거라 그런 것 같아요.

**Comment by dotoleeoak** [comment]
알아보니까 constructor based로 바꾸는 게 좋을 것 같네요. 아무나 PR 열어주시면 감사하겠습니다~~ 🙏
